services:
  mailcatcher:
    image: dockage/mailcatcher:0.10.0
    ports:
      - :1025
      - 1080:1080

  msmtp:
    container_name: msmtp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.ini:/config.ini:ro
      - ./message.txt.jinja2:/message.txt.jinja2:ro
      - ./sendmails.sh:/sendmails.sh:ro
      - ./message-sem2.txt.jinja2:/message-sem2.txt.jinja2:ro
      - ./message-2024.txt.jinja2:/message-2024.txt.jinja2:ro
      - ./sendmails-sem2.sh:/sendmails-sem2.sh:ro
      - ./sendmails-2024.sh:/sendmails-2024.sh:ro
      - ./resources:/resources:ro
      - ./out:/out

  msmtp2:
    image: dmitryrck/msmtp
    volumes:
      - ./config.ini:/config.ini:ro

  # mail:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './config.ini:/config.ini'
  #   ports:
  #     - '1025:1025'
  #     - '1080:1080'
