version: '3.8'

services:
  mail:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './config.ini:/config.ini'
    ports:
      - '1025:1025'
      - '127.0.0.1:8080:1080'
